### ISSUE TITLE
Cannot Compile Tapescript in Linux

### ISSUE THREAD

**Issue by rcalxrc08** [compatibl/tapescript#3]
I do not find any installation guide for this library, so i decided to try on my own, these are the steps that i follow:
1) i download the tapescript library from github (using `git clone https://github.com/compatibl/tapescript.git`).
2) i run ./autogen.sh inside the tapescript folder, getting the following output:
`libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, config.`
`libtoolize: copying file config/ltmain.sh`
`libtoolize: Consider adding AC_CONFIG_MACRO_DIRS([m4]) to configure.ac,`
`libtoolize: and rerunning libtoolize and aclocal.`
`libtoolize: Consider adding -I m4 to ACLOCAL_AMFLAGS in Makefile.am.`
`configure.ac:23: installing config/compile`
`configure.ac:26: installing config/config.guess`
`configure.ac:26: installing config/config.sub`
`configure.ac:5: installing config/install-sh`
`configure.ac:5: installing config/missing`
`tapescript/cpp/cl/tape/examples/Makefile.am: installing config/depcomp`

`Run the command ./configure --help for information on options
that can change the behavior of the library.`

3) without concerning the last output i run `./configure`, getting the following output:
`checking for a BSD-compatible install... /usr/bin/install -c`
`checking whether build environment is sane... yes`
`checking for a thread-safe mkdir -p... /bin/mkdir -p`
`checking for gawk... gawk`
`checking whether make sets $(MAKE)... yes`
`checking whether make supports nested variables... yes`
`checking for gawk... (cached) gawk`
`checking for gcc... gcc`
`checking whether the C compiler works... yes`
`checking for C compiler default output file name... a.out`
`checking for suffix of executables... `
`checking whether we are cross compiling... no`
`checking for suffix of object files... o`
`checking whether we are using the GNU C compiler... yes`
`checking whether gcc accepts -g... yes`
`checking for gcc option to accept ISO C89... none needed`
`checking whether gcc understands -c and -o together... yes`
`checking for style of include used by make... GNU`
`checking dependency style of gcc... gcc3`
`checking for g++... g++`
`checking whether we are using the GNU C++ compiler... yes`
`checking whether g++ accepts -g... yes`
`checking dependency style of g++... gcc3`
`checking how to run the C preprocessor... gcc -E`
`checking build system type... x86_64-pc-linux-gnu`
`checking host system type... x86_64-pc-linux-gnu`
`checking how to print strings... printf`
`checking for a sed that does not truncate output... /bin/sed`
`checking for grep that handles long lines and -e... /bin/grep`
`checking for egrep... /bin/grep -E`
`checking for fgrep... /bin/grep -F`
`checking for ld used by gcc... /usr/bin/ld`
`checking if the linker (/usr/bin/ld) is GNU ld... yes`
`checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B`
`checking the name lister (/usr/bin/nm -B) interface... BSD nm`
`checking whether ln -s works... yes`
`checking the maximum length of command line arguments... 1572864`
`checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop`
`checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop`
`checking for /usr/bin/ld option to reload object files... -r`
`checking for objdump... objdump`
`checking how to recognize dependent libraries... pass_all`
`checking for dlltool... no`
`checking how to associate runtime and link libraries... printf %s\n`
`checking for ar... ar`
`checking for archiver @FILE support... @`
`checking for strip... strip`
`checking for ranlib... ranlib`
`checking command to parse /usr/bin/nm -B output from gcc object... ok`
`checking for sysroot... no`
`checking for a working dd... /bin/dd`
`checking how to truncate binary pipes... /bin/dd bs=4096 count=1`
`checking for mt... mt`
`checking if mt is a manifest tool... no`
`checking for ANSI C header files... yes`
`checking for sys/types.h... yes`
`checking for sys/stat.h... yes`
`checking for stdlib.h... yes`
`checking for string.h... yes`
`checking for memory.h... yes`
`checking for strings.h... yes`
`checking for inttypes.h... yes`
`checking for stdint.h... yes`
`checking for unistd.h... yes`
`checking for dlfcn.h... yes`
`checking for objdir... .libs`
`checking if gcc supports -fno-rtti -fno-exceptions... no`
`checking for gcc option to produce PIC... -fPIC -DPIC`
`checking if gcc PIC flag -fPIC -DPIC works... yes`
`checking if gcc static flag -static works... yes`
`checking if gcc supports -c -o file.o... yes`
`checking if gcc supports -c -o file.o... (cached) yes`
`checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes`
`checking whether -lc should be explicitly linked in... no`
`checking dynamic linker characteristics... GNU/Linux ld.so`
`checking how to hardcode library paths into programs... immediate`
`checking whether stripping libraries is possible... yes`
`checking if libtool supports shared libraries... yes`
`checking whether to build shared libraries... yes`
`checking whether to build static libraries... yes`
`checking how to run the C++ preprocessor... g++ -E`
`checking for ld used by g++... /usr/bin/ld -m elf_x86_64`
`checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes`
`checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes`
`checking for g++ option to produce PIC... -fPIC -DPIC`
`checking if g++ PIC flag -fPIC -DPIC works... yes`
`checking if g++ static flag -static works... yes`
`checking if g++ supports -c -o file.o... yes`
`checking if g++ supports -c -o file.o... (cached) yes`
`checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes`
`checking dynamic linker characteristics... (cached) GNU/Linux ld.so`
`checking how to hardcode library paths into programs... immediate`
`checking whether C compiler accepts -std=c++11... yes`
`checking whether g++ supports C++11 features by default... no`
`checking whether g++ supports C++11 features with -std=gnu++11... yes`
`checking for emacs... no`
`checking for xemacs... no`
`checking where .elc files should go... ${datadir}/emacs/site-lisp`
`checking that generated files are newer than configure... done`
`configure: creating ./config.status`
`config.status: creating Makefile`
`config.status: creating tapescript/cpp/cl/tape/examples/Makefile`
`config.status: executing depfiles commands`
`config.status: executing libtool commands`.
4) i finally run `make all`, obtaining the following output:
(the output was too huge to be in a page) http://pastebin.com/5219FE0Z
Do you have any idea? 
i have already tried in different Linux Computers with different Distros, getting the same result.
I have already tried to add the flag that the compilers tells me to add in configure.ac and makefile.am getting the same results.

**Comment by stefanofiorentino** [comment]
same issue here.
looking for the root cause yields no results but strange behavior of __GNUC__ preprocessor flag.

my system confs are:
gcc-6, autotools (HomeBrew)
Mac OS X 10.11.6

**Comment by compatibl-dev** [comment]
Thank you for reporting this. We reproduced and fixed the issue, and will post the patch in 1-2 days after checking it does not break any other compiler versions. - CompatibL Team

**Comment by compatibl-dev** [comment]
@rcalxrc08, @stefanofiorentino:

We pushed a fix for gcc compilation errors on Linux. Please use the following build instructions:

1)	Run: ./autogen.sh
2)	Run: ./configure
3)	Run: make
4)	Executable file for tapescript tests: tapescript/cpp/cl/tape/examples/tape_example

You will need the following packages: g++, make, automake, libtool, autoconf, autoconf-archive

Best regards
CompatibL Team

**Comment by rcalxrc08** [comment]
It works, Thank you very much!
